#ifndef APP_XDMA_CFG_H_
#define APP_XDMA_CFG_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "app_cisdp_cfg.h"

#define WDMA2_CYCLIC_BUF_CNT 1

#if defined(CDM_WAKEUP)
#define WDMA1_SIZE      (SENCTRL_SENSOR_WIDTH*SENCTRL_SENSOR_HEIGHT)
#else
#define WDMA1_SIZE      0
#endif

#if (DP_WDMA_SIZE_CFG == JPEG_ENC_YUV400_4X)
#define WDMA2_SLOT_SIZE (((613+(DP_JPEG_ENC_WIDTH/16)*(DP_JPEG_ENC_HEIGHT/16)*64+35)>>2)<<2) // 0x12E88
#define WDMA3_SIZE      (DP_JPEG_ENC_WIDTH*DP_JPEG_ENC_HEIGHT)
#elif (DP_WDMA_SIZE_CFG == JPEG_ENC_YUV400_10X)
#define WDMA2_SLOT_SIZE (((613+(DP_JPEG_ENC_WIDTH/16)*(DP_JPEG_ENC_HEIGHT/16)*24+35)>>2)<<2) // 0x7308
#define WDMA3_SIZE      (DP_JPEG_ENC_WIDTH*DP_JPEG_ENC_HEIGHT)
#elif (DP_WDMA_SIZE_CFG == JPEG_ENC_YUV420_4X)
#define WDMA2_SLOT_SIZE (((623+(DP_JPEG_ENC_WIDTH/16)*(DP_JPEG_ENC_HEIGHT/16)*96+35)>>2)<<2) //0x1C490
#define WDMA3_SIZE      (DP_JPEG_ENC_WIDTH*DP_JPEG_ENC_HEIGHT + (DP_JPEG_ENC_WIDTH*DP_JPEG_ENC_HEIGHT/2))
#elif (DP_WDMA_SIZE_CFG == JPEG_ENC_YUV420_10X)
#define WDMA2_SLOT_SIZE (((623+(DP_JPEG_ENC_WIDTH/16)*(DP_JPEG_ENC_HEIGHT/16)*38+35)>>2)<<2) // 0xB4B0
#define WDMA3_SIZE      (DP_JPEG_ENC_WIDTH*DP_JPEG_ENC_HEIGHT + (DP_JPEG_ENC_WIDTH*DP_JPEG_ENC_HEIGHT/2))
#elif (DP_WDMA_SIZE_CFG == JPEG_ENC_YUV422_4X)
#define WDMA2_SLOT_SIZE (((623+(DP_JPEG_ENC_WIDTH/16)*(DP_JPEG_ENC_HEIGHT/16)*128+35)>>2)<<2) //0x25A90
#define WDMA3_SIZE      (DP_JPEG_ENC_WIDTH*DP_JPEG_ENC_HEIGHT + DP_JPEG_ENC_WIDTH*DP_JPEG_ENC_HEIGHT)
#elif (DP_WDMA_SIZE_CFG == JPEG_ENC_YUV422_10X)
#define WDMA2_SLOT_SIZE (((623+(DP_JPEG_ENC_WIDTH/16)*(DP_JPEG_ENC_HEIGHT/16)*50+35)>>2)<<2) // 0xECF0
#define WDMA3_SIZE      (DP_JPEG_ENC_WIDTH*DP_JPEG_ENC_HEIGHT + DP_JPEG_ENC_WIDTH*DP_JPEG_ENC_HEIGHT)
#else
#define WDMA2_SLOT_SIZE 0
#define WDMA3_SIZE      0
#endif

#define JPEG_AUTOFILL_SIZE      100 //100 bytes

#ifdef __cplusplus
}
#endif

#endif /* APP_XDMA_CFG_H_ */
